name: Close Stale Issues
uses: actions/stale@v10.1.1
with:
  days-before-issue-stale: 30
  days-before-pr-stale: 30
  days-before-issue-close: 7
  days-before-pr-close: 7

  stale-issue-message: >
    This issue has been marked as stale due to inactivity.
    If this is still relevant, please comment to keep it open.

  close-issue-message: >
    Closing this issue due to prolonged inactivity.
    Feel free to reopen or create a new issue if needed.

  exempt-issue-labels: bug
  only-issues: true