name: First interaction
uses: actions/first-interaction@v1.3.0
with:
  issue-message: |
    **Thanks for your first issue!**
    
    Please make sure you have read the [README](./README.md)
  pr-message: |
    **Thanks for your first pull request!**